spring.application.name=SmartDeliveryPlatform

spring.datasource.url=jdbc:postgresql://localhost:5432/smart_delivery
spring.datasource.username=admin
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.root=warn
logging.level.org.springframework=warn
logging.level.org.hibernate=warn

spring.jpa.open-in-view=false